FROM ubuntu:jammy

WORKDIR /code

COPY . /code

RUN apt update && \
    apt install nodejs npm python3 -y

RUN npm install && \
    npm run build

EXPOSE 8000
ENTRYPOINT ["python3", "-m", "http.server", "-d", "dist"]
