name: Deploy App
run-name: ${{ github.event.head_commit.message }}

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Build App Container
        shell: bash
        run: |
          cd angular-landing-page
          echo "Building Container Image"
          docker build --no-cache -t myapp-opt -f ../dockerfile-optimized .

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Deploy New Image
        shell: bash
        run: |
          echo "Restarting Contaier"
          docker restart myapp
          echo "Clearing stale images"
          docker image prune -f
