name: Deploy App
run-name: ${{ github.event.head_commit.message }}

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:

  scan:
    name: Code Scan
    runs-on: self-hosted
    steps:
      - name: Message
        shell: bash
        run: echo "Scanning Code"

  unit-test:
    name: Unit Test
    runs-on: self-hosted
    needs: [scan]
    steps:
      - name: Message
        shell: bash
        run: echo "Running Unit Test"

  e2e-test:
    name: E2E Test
    runs-on: self-hosted
    needs: [unit-test]
    steps:
      - name: Message
        shell: bash
        run: echo "Running E2E Tests"

  build:
    name: Build
    runs-on: self-hosted
    needs: [e2e-test]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
      - name: Login to Github container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Lowercase repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          context: ./angular-landing-page
          file: ./dockerfile-optimized
      - name: Build App Container
        shell: bash
        run: |
          cd angular-landing-page
          echo "Building Container Image"
          docker build --no-cache -t angular-landing-page -f ../dockerfile-optimized .

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Deploy New Image
        shell: bash
        run: |
          echo "Restarting Contaier"
          docker container stop myapp || true
          docker container rm myapp || true
          docker run -d --restart=unless-stopped -p 80:80 --name myapp myapp-opt
          echo "Clearing stale images"
          docker image prune -f

  notify:
    name: Notify User about release
    runs-on: self-hosted
    needs: [deploy]
    steps:
      - name: Message
        shell: bash
        run: echo "Notifying Users"
